export const keywords: string[] = [
  // Brand
  "fixfx",
  "fixfx-wiki",
  "fixfx docs",
  "fixfx documentation",
  "fixfx guide",
  "fixfx tutorial",
  "fixfx wiki",
  "fixfx development",
  "fixfx tools",
  "fixfx resources",

  // FiveM
  "fivem",
  "fivem development",
  "fivem scripting",
  "fivem lua",
  "fivem javascript",
  "fivem c#",
  "fivem api",
  "fivem server",
  "fivem resources",
  "fivem framework",
  "fivem tutorial",
  "fivem guide",
  "fivem docs",
  "fivem documentation",
  "fivem community",
  "fivem modding",
  "fivem server development",
  "fivem server management",
  "fivem server hosting",
  "fivem server setup",

  // Development
  "lua",
  "javascript",
  "typescript",
  "c#",
  "csharp",
  "game development",
  "game modding",
  "server development",
  "server management",
  "server hosting",
  "server setup",
  "game scripting",
  "game api",
  "game framework",
  "game resources",
  "game tools",
  "game utilities",
  "game optimization",
  "game performance",
  "game debugging",
  "game profiling",
  "game testing",
  "game documentation",
  "game tutorial",
  "game guide",
  "game wiki",
  "game community",
  "game support",
  "game help",
  "game resources",
  "game tools",
  "game utilities",
  "game optimization",
  "game performance",
  "game debugging",
  "game profiling",
  "game testing",
  "game documentation",
  "game tutorial",
  "game guide",
  "game wiki",
  "game community",
  "game support",
  "game help",

  // Tools & Utilities
  "profiler",
  "debugger",
  "optimizer",
  "performance",
  "testing",
  "documentation",
  "tutorial",
  "guide",
  "wiki",
  "community",
  "support",
  "help",
  "resources",
  "tools",
  "utilities",
  "optimization",
  "performance",
  "debugging",
  "profiling",
  "testing",
  "documentation",
  "tutorial",
  "guide",
  "wiki",
  "community",
  "support",
  "help",

  // Community
  "discord",
  "github",
  "forum",
  "community",
  "support",
  "help",
  "resources",
  "tools",
  "utilities",
  "optimization",
  "performance",
  "debugging",
  "profiling",
  "testing",
  "documentation",
  "tutorial",
  "guide",
  "wiki",
  "community",
  "support",
  "help"
];
