name: Build Website
on:
  push:
    branches: [master, development]

jobs:
  build_test:
    # Changed from self-hosted to GitHub-hosted runner
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - uses: actions/setup-node@v3
        with:
          node-version: 20.18.0
          cache: 'npm'
      # Add caching to speed up npm install
      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install dependencies
        run: npm ci
      - name: Build application
        run: npm run build
      # Optionally add a notification if the build succeeds
      - name: Notify success
        run: echo "Build completed successfully!"